spring.application.name=neobank360
spring.datasource.url=jdbc:mysql://localhost:3306/neobank_db
spring.datasource.username=neobank_user
spring.datasource.password=NeoBank360#

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true